### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by likezjuisee** [hraban/opus#16]
/tmp/go-build982820362/command-line-arguments/_obj/exe/main: symbol lookup error: /usr/lib/libopusfile.so.0: undefined symbol: opus_pcm_soft_clip
exit status 127

**Comment by hraban** [comment]
can you give more info?

**Comment by hraban** [comment]
Hi like,

I'm afraid I'm going to have to close this issue until I get more information about what's happening, exactly.

Wild guess: it looks like your system-wide opus lib is out of sync with the headers (opus.h). Did you add get the headers from source control somewhere, instead of from your package manager? If it's linux, try to install something like libopus-dev.

Good luck
