### ISSUE TITLE
How can I play opus codec audio by using portaudio?

### ISSUE THREAD

**Issue by naixsky** [hraban/opus#20]
Dears,

As title, I have a project need play opus audio. 
What golang player library can do this?

And how can I play audio with pcm format?
Could anyone give me some suggestions?

Thx a lot!

**Comment by hraban** [comment]
not sure, to be honest. I never actually play back audio data using Go, I just transcode it. you'll have to decode the opus to PCM data, as you identified, but once you've got that you'll need to, somehow, connect to a.. audio daemon or something? depends on the OS, probably. sounds like a can of worms :)

Closing this question because playback is not part of this lib; just decoding.

Good luck!
