### ISSUE TITLE
There is a difference between an opus stream (which is an ogg/opus stream) and raw opus data. .opus files are really .ogg files with opus data, which this package doesn't provide a way to write. It does have a reader for it (Stream type), but no writer yet (never bothered to because I haven't needed it so far, but feel free to submit a PR).

### ISSUE THREAD

**Issue by litao09h** [hraban/opus#22]
There is a difference between an opus stream (which is an ogg/opus stream) and raw opus data. .opus files are really .ogg files with opus data, which this package doesn't provide a way to write. It does have a reader for it (Stream type), but no writer yet (never bothered to because I haven't needed it so far, but feel free to submit a PR).

_Originally posted by @hraban in https://github.com/hraban/opus/issues/15#issuecomment-331120868_

**Comment by litao09h** [comment]
If you don't write a file, how do you know if the encoding is correct?

**Comment by hraban** [comment]
Me personally, I only ever used this for two things:

1. decoding a .opus stream (i.e. ogg/opus)
2. encoding raw opus data and sending it to another client that would decode it, raw, to PCM, and play it back.

In the second case I was in control of both server and client, and only used opus to reduce the size of packets on the network. No need to implement Ogg streams since I already had a message based stream setup.
