### ISSUE TITLE
transfer pcm to raw opus

### ISSUE THREAD

**Issue by litao09h** [hraban/opus#23]
I tried to convert pcm to raw opus(not oggOpus) but it didn't take effect.

```
const sampleRate = 16000
const channels = 1 // mono; 2 for stereo
const bufferSize = 1000 // choose any buffer size you like. 1k is plenty

func main(){
	enc, err := opus.NewEncoder(sampleRate, channels, opus.AppAudio)
	if err != nil {
		panic(err)
	}
	if err != enc.SetBitrate(25600) {
		panic(err)
	}
	if err != enc.SetComplexity(10) {
		panic(err)
	}
	if err !=enc.SetMaxBandwidth(opus.Wideband){
		panic(err)
	}


        fb,err := os.Open("1549937764922.pcm")
	if err != nil {
		panic(err)
	}
	var totalOpus bytes.Buffer
	for {
		pcm := make([]int16, 320)
		err = binary.Read(fb, binary.LittleEndian, &pcm)
		if err == io.EOF || err == io.ErrUnexpectedEOF {
			break
		}
		if err != nil {
			fmt.Printf("%+v\n", err)
			break
		}
		frameSize := len(pcm)
		frameSizeMs := float32(frameSize) / channels * 1000 / sampleRate
		switch frameSizeMs { //
		case 2.5, 5, 10, 20, 40, 60:
			// Good.
		default:
			panic(fmt.Sprintf("Illegal frame size: %d bytes (%f ms)", frameSize, frameSizeMs))
		}
		data := make([]byte, bufferSize)
		n, err := enc.Encode(pcm, data)
		if err != nil {
			panic(err)
		}
		fmt.Printf("readPcm_len=%d,encodeOpus_len=%d\n",frameSize,n)
		totalOpus.Write(data[:n])
	}
	ioutil.WriteFile("encoded.opus",totalOpus.Bytes(),os.ModePerm)
}
```

**Comment by hraban** [comment]
hi @litao09h , thanks for getting in touch. could you please help me make this issue easier to understand by:

1. cleaning up the formatting. currently it looks half formatted, half not.
2. posting any relevant error messages and data
3. explaining what you're trying to do (for example: "I take raw PCM data from file X, which I obtained by doing Y, and I want to store raw Opus packets in file Z")
4. explaining what you *expected* to see (for example: A file Z which, when I pass it back through decoder.Decode creates a PCM file very close to the original file)
5. explaining what you saw, instead. (for example: error message MMM).

Because of the size of this example you posted, by the way, I'm going to guess the problem is almost certainly somewhere in your code. There is a lot of sample code in the _test.go files; I strongly recommend having a look at those and trying to adapt them to fit your needs.

If the problem persists, please report back and we'll sort it out.

Good luck!

(好好儿干啊 😀)

**Comment by litao09h** [comment]
Thanks for the quick reply and patient guidance😁
1，Done
2，the code is ok，no error message. using the opus official tool opus_demo to decode the file encoded.opus failed:
➜  aa_opus git:(master) ✗ ~/opus/opus_demo -d 16000 1 encoded.opus test.pcm
libopus 1.2.1
Decoding with 16000 Hz output (1 channels)
Invalid payload length: -1199843657
average bitrate:                 nan kb/s
maximum bitrate:              -0.000 kb/s
bitrate standard deviation:      nan kb/s

3， I take raw PCM data from file 1549937764922.pcm, which I obtained from our business (ffplay ok), and I want to store raw Opus packets in file encoded.opus.

4，I expect to decode encoded.opus to pcm with opus_demo and very close to the original file。

**Comment by hraban** [comment]
你好litao 😀

thanks for that. The code seems functional at a glance (although you have a very peculiar error matching pattern at the top :) I would suggest doing: `if err = doSomething(); err != nil { .... }` instead). My biggest question right now is around opus_demo, which I have never used as a tool. I found some documentation here: https://chromium.googlesource.com/chromium/deps/opus/+/1.0.1/README which says:

> input and output are little-endian signed 16-bit PCM files or opus
> bitstreams with simple **opus_demo proprietary framing**.

(emphasis mine)

Are you sure the opus_demo tool is capable of decoding *raw* opus data? It seems to me that it would only decode a type of opus stream which it has, itself, encoded. A wrapper around raw opus data which is not Ogg, but something else, entirely.

How do we test this hypothesis?

1. create a simple decode.go which takes the file you have created and decodes it to raw PCM (i.e. what you are currently trying to use opus_demo for). The decoder_test.go and opus_test.go files contain a lot of relevant code.
2. use this program to decode your .opus file and see what happens. Does it work? then you are almost certain that the .opus data is valid.
3. use opus_demo to *encode* your own raw .pcm file, then pass *that* file through your new decoder that you created. does it work? if not, it's probably because it's not raw Opus, but a proprietary format

Good luck! 🙂

**Comment by litao09h** [comment]
thx.
opus_demo, reference to this project: [ https://github.com/xiph/opus](url)
opus_demo test files (来一首世上只有妈妈好)
[https://raw.githubusercontent.com/litao09h/download/master/opus_test_data.zip](url)
it works fine.

➜  opus git:(defbc370) ✗ ./opus_demo -e audio 16000 1 25600 1549937764922.pcm 1549937764922.opus
libopus 1.2.1
Encoding 16000 Hz input at 64.000 kb/s in auto bandwidth with 320-sample frames.
average bitrate:              60.219 kb/s
maximum bitrate:             104.000 kb/s
active bitrate:               71.471 kb/s
bitrate standard deviation:   13.161 kb/s
➜  opus git:(defbc370) ✗ ll 1549937764922.pcm 1549937764922.opus
total 352
-rw-r--r--@ 1 litao  staff   16573  7  1 18:37 1549937764922.opus
-rw-r--r--  1 litao  staff  158400  7  1 18:37 1549937764922.pcm
➜  opus git:(defbc370)

**Comment by hraban** [comment]
Yes, but what is that .opus file, now? Is it actually *raw opus blocks*? I suspect that there is custom metadata in there.

Note that Opus is a block encoding and you need a message based stream to store it; you can't just save it as a raw stream because you will lose the block boundaries. This, and the documentation I posted earlier, suggest that **the opus_demo tool probably does not store raw opus blocks**.

As I said: please write a simple decoder and use that to try and decode that .opus file you created using opus_tool.

**Comment by litao09h** [comment]
decode error：panic: opus: corrupted stream.
I kown what you mean , you are right. 
I will discuss the solution with other colleagues.
thank you so much 😝

**Comment by hraban** [comment]
👍
