### ISSUE TITLE
How to complie in cross platform?

### ISSUE THREAD

**Issue by juicechu** [hraban/opus#34]
I try to go build for arm cpu，but output display error message. And go build for x86 cpu is ok.
```
env GOOS=linux GOARCH=arm go build   
# github.com/hraban/opus
/home/juice/code/golang/pkg/mod/github.com/hraban/opus@v0.0.0-20200710132758-e28f8214483b/streams_map.go:32:23: undefined: Stream
/home/juice/code/golang/pkg/mod/github.com/hraban/opus@v0.0.0-20200710132758-e28f8214483b/streams_map.go:36:40: undefined: Stream
/home/juice/code/golang/pkg/mod/github.com/hraban/opus@v0.0.0-20200710132758-e28f8214483b/streams_map.go:42:30: undefined: Stream
/home/juice/code/golang/pkg/mod/github.com/hraban/opus@v0.0.0-20200710132758-e28f8214483b/streams_map.go:53:31: undefined: Stream
```
Then i try to add build options `-tags nolibopusfile`
```
env GOOS=linux GOARCH=arm go build -tags nolibopusfile 
go build github.com/hraban/opus: build constraints exclude all Go files in /home/juice/code/golang/pkg/mod/github.com/hraban/opus@v0.0.0-20200710132758-e28f8214483b

```

**Comment by hraban** [comment]
你好 ：）

I've never tried this, but from what I understand CGO is disabled for cross compiling:

> The cgo tool is enabled by default for native builds on systems where it is expected to work. It is disabled by default when cross-compiling. You can control this by setting the CGO_ENABLED environment variable when running the go tool: set it to 1 to enable the use of cgo, and to 0 to disable it. The go tool will set the build constraint "cgo" if cgo is enabled. The special import "C" implies the "cgo" build constraint, as though the file also said "// +build cgo". Therefore, if cgo is disabled, files that import "C" will not be built by the go tool. (For more about build constraints see https://golang.org/pkg/go/build/#hdr-Build_Constraints). 

- https://golang.org/cmd/cgo/

You'll need to figure out how to make pkgconfig work for cross compilation, as well, since this opus wrapper relies on pkgconfig to find the header files and libraries to link to.

All in all, this won't be easy. If you do succeed, let me know :) I can add the instructions to the README.

I'm closing this ticket because cross compiling CGO is a separate problem from what this package tries to solve.

Good luck!

**Comment by hraban** [comment]
(some background info for clarity: this package , github.com/hraban/opus, is just a GO ↔ C translation layer. The real opus work is done by libopus, a library written in C and maintained by xiph.org. Cross compiling Go is easy, but cross compiling CGO means you need to cross compile the libopus header files as well, so you'll need a cross compiling C compiler. That's why this is tricky.)

**Comment by juicechu** [comment]
Thank for you answer my question. I got it . I will continue research how to cross compiling CGO. 

if i get some advancement, i will write down it.

**Comment by hraban** [comment]
Let me know if you make it work. I'd love to add a section to the README about it.

**Comment by sidharthrajaram** [comment]
Encountering the same issue, curious if there was a fix @hraban @juicechu ? Thanks.
