### ISSUE TITLE
Byte slice to int16 slice. 

### ISSUE THREAD

**Issue by Lighty0410** [hraban/opus#41]
Hey everyone! Currently i'm trying to transcode ADTS to OPUS. And here's the problem. 
I'm using this library to split an ADTS stream to PCMs - https://github.com/winlinvip/go-fdkaac . But PCMs it returns are []byte, not []int16. 
What's the correct approach than to encode a bunch of PCMs in []byte (not []int16) ?  
Thanks in advance!

**Comment by hraban** [comment]
Hi @Lighty0410 :)

I'm surprised by that API. PCM data is not bytes, it's (signed) int16 or float32. I don't know this lib, but I did some digging, and it casts the char * pcm buffer to a `INT_PCM *` type array here: https://github.com/winlinvip/go-fdkaac/blob/2654f5a0cc2e3e9584a0c7f5ccae9d64f3bf957d/fdkaac/dec.go#L127

If you look at the backing C library, it defines `INT_PCM` as a `SHORT` here: https://github.com/mstorsjo/fdk-aac/blob/f285813ec15e7c6f8e4839c9eb4f6b0cd2da1990/libSYS/include/machine_type.h#L226 , which is a "Data type representing 2 byte signed integer on all supported".

Basically, this is a raw pointer cast without checking the byte order. I don't think this is safe, and even if it were, it's unnecessary, because they could just accept an int16[] instead of a byte[] to begin with and do away with the cast.

Honestly you're probably best off forking this lib, fixing the API and removing that cast. You can always submit a PR, see if they want it.

While you're at it, I would advise removing the allocation of the pcm buffer in the wrapper lib. You want the user of the lib to pass their buffer to your decoder (like the underlying C library does, and io.Reader, and this lib). This allows you to allocate once and reuse that buffer over and over again. See https://github.com/winlinvip/go-fdkaac/blob/2654f5a0cc2e3e9584a0c7f5ccae9d64f3bf957d/fdkaac/dec.go#L361 .

Good luck!

**Comment by hraban** [comment]
Closing this ticket.
