### ISSUE TITLE
implicit declaration of function 'OPUS_GET_IN_DTX'

### ISSUE THREAD

**Issue by BrianMwas** [hraban/opus#52]
After trying to build my Go application using Docker I got the following error, not sure why am getting it though. Here's the error
`#12 24.31 /go/pkg/mod/github.com/hraban/opus@v0.0.0-20230925203106-0188a62cb302/encoder.go: In function 'bridge_encoder_get_in_dtx':
#12 24.31 /go/pkg/mod/github.com/hraban/opus@v0.0.0-20230925203106-0188a62cb302/encoder.go:31:30: warning: implicit declaration of function 'OPUS_GET_IN_DTX'; did you mean 'OPUS_GET_DTX'? [-Wimplicit-function-declaration]
#12 24.31   return opus_encoder_ctl(st, OPUS_GET_IN_DTX(in_dtx));
#12 24.31                               ^~~~~~~~~~~~~~~
#12 24.31                               OPUS_GET_DTX
#12 35.74 # command-line-arguments
#12 35.74 /usr/local/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
#12 35.74 /usr/bin/ld: /tmp/go-link-2185058262/000007.o: in function `bridge_encoder_get_in_dtx':
#12 35.74 /go/pkg/mod/github.com/hraban/opus@v0.0.0-20230925203106-0188a62cb302/encoder.go:31: undefined reference to `OPUS_GET_IN_DTX'
#12 35.74 collect2: error: ld returned 1 exit status`

To be able to reproduce the following error you, I used the following Dockerfile commands
`FROM golang:1.19-buster AS builder

WORKDIR /app

# Copy your Go source code into the container
COPY . .

# Install Opus and any other dependencies specific to your Alpine-based image
RUN apt-get update && apt-get -y install libopus-dev libopusfile-dev

# Build the Go binary
RUN go build -o main main.go`
That's how you reproduce it

**Comment by hraban** [comment]
It sounds like you might be using an old version of opus. GET_IN_DTX was introduced in 1.3.1: https://opus-codec.org/docs/opus_api-1.3.1/group__opus__genericctls.html#ga9af68dcfb4f136dd91b1050658d559ca . Try updating your alpine base image. If that doesn't work you'll have to wait for a new alpine release, or install the latest libopus yourself.

**Comment by BrianMwas** [comment]
@hraban what is the correct version to use, I thought the go-get should pick the most recent version. Is there a specific version I should use, also are there any examples I can review? Because this has bothered me since Friday any help would be appreciated

**Comment by hraban** [comment]
The package you're commenting on right now is a _wrapper_ package; just a translation layer between Go and C. You still need a C library, which you install using `apt-get install ....` (or whatever package manager you use). That is not provided by this package, which (again) is just a wrapper, so it doesn't provide actual opus decoding of any kind: just a translation from Go to the actual native library that does the actual decoding. And _that_ library must be the right version (1.3.1).

You can also try and dig into this package's history and find an older version that didn't use GET_IN_DTX yet, maybe that can work with your older library.

I can't help you any further because, fundamentally, you're asking the wrong person; I don't control your OS, or your package manager, or the libraries you install. That's kinda the whole point: this is just an independent wrapper which allows / requires you to bring your own library. For actual support with this you'll have to ask somewhere like StackOverflow, or a relevant discord or IRC channel, for help on how to install the latest version of the opus library on your system.

**Comment by BrianMwas** [comment]
Thank you, I have been trying to use it with docker but I get your point, thanks

**Comment by Modestying** [comment]
> The package you're commenting on right now is a _wrapper_ package; just a translation layer between Go and C. You still need a C library, which you install using `apt-get install ....` (or whatever package manager you use). That is not provided by this package, which (again) is just a wrapper, so it doesn't provide actual opus decoding of any kind: just a translation from Go to the actual native library that does the actual decoding. And _that_ library must be the right version (1.3.1).
> 
> You can also try and dig into this package's history and find an older version that didn't use GET_IN_DTX yet, maybe that can work with your older library.
> 
> I can't help you any further because, fundamentally, you're asking the wrong person; I don't control your OS, or your package manager, or the libraries you install. That's kinda the whole point: this is just an independent wrapper which allows / requires you to bring your own library. For actual support with this you'll have to ask somewhere like StackOverflow, or a relevant discord or IRC channel, for help on how to install the latest version of the opus library on your system.


Please add `right version (1.3.1)` in `Readme.md`. @hraban

The link in Readme.md `-- https://opus-codec.org/docs/opus_api-1.1.3/group__opus__encoder.html` is really confusing. 

Besides, consider deployment without network, i'd like to compile source code without `apt` ,so that I can run like
 ```
CGO_FLAGS="-I${PWD}/include/opus" \
 CGO_LDFLAGS="-L${PWD}/libs/opus -Wl,rpath=${PWD}/libs/opus" \
 go run talk.go` 
```

LIbs I compile:
- ogg-1.3.5
- opus-1.3.1
- opusfile-0.12

Hope it can be helpful for you

**Comment by hraban** [comment]
good point on the doc link @Modestying , although I'm a bit confused as to your second point: what do you mean by "deployment without network"? I don't think I currently do any kind of network, or do I? Do you mean removing the requirement on pkg-config?

**Comment by Modestying** [comment]
> good point on the doc link @Modestying , although I'm a bit confused as to your second point: what do you mean by "deployment without network"? I don't think I currently do any kind of network, or do I? Do you mean removing the requirement on pkg-config?

No ,second point is for command `sudo apt-get install pkg-config libopus-dev libopusfile-dev`.I'm not  familiar with `pkg-config`,just for `libopus-dev` and `libposfile-dev`.I mean libs.

- Now, I can work on computer with network, and install libs quickly with `apt-install`
- But sometimes, devolpers need to work without network for company rules(surprising but truth)
- Special version.Install lib env with `apt install` is quickly for personal devops,but I think not good for `team`.We must  ensure everyone work with  same lib version.
- Besides,I think it's also necessary to know `right libs version`  for write `project docs` and `deployment`.I can't say  `I don't know` when others ask me about lib's info.

Just some opinions for my personal.

**Comment by hraban** [comment]
This wrapper works with _any_ 1.x version of opus, which for all intents and purposes is all of opus. When they release libopus2 then I'll add a notice, but for now there is no point because all of opus is compatible with the 1.x API.

As to apt-get: I consider it standard enough that if your system doesn't have it, you're probably also skilled enough to fork this repo and adapt it as you see fit. It's MIT licensed so by all means feel free and go wild :)

**Comment by Modestying** [comment]
> This wrapper works with _any_ 1.x version of opus, which for all intents and purposes is all of opus. When they release libopus2 then I'll add a notice, but for now there is no point because all of opus is compatible with the 1.x API.
> 
> As to apt-get: I consider it standard enough that if your system doesn't have it, you're probably also skilled enough to fork this repo and adapt it as you see fit. It's MIT licensed so by all means feel free and go wild :)

thx for your answer
